# Default storage, exemplifies simplisity, will create a /mnt/stateful_partition dir on host 
#  and use this for Solace message spool 
solace:
  redundancy: false
  size: dev100
# Current options are [gcp|aws]
cloudProvider: gcp
image:
  repository: solace/solace-pubsub-standard
  tag: latest
  pullPolicy: IfNotPresent
filepaths:
  configmap: "/mnt/disks/solace"
  secrets: "/mnt/disks/secrets"
service:
  internal: false
  type: LoadBalancer
  externalPort:
    - port: 22
      protocol: TCP
      name: ssh
      targetport: 2222
    - port: 8080
      protocol: TCP
      name: semp
    - port: 55555
      protocol: TCP
      name: smf
    - port: 943
      protocol: TCP
      name: semptls
      targetport: 60943
    - port: 80
      protocol: TCP
      name: web
      targetport: 60080
    - port: 443
      protocol: TCP
      name: webtls
      targetport: 60443
  internalPort:
    - port: 2222
      protocol: TCP
    - port: 8080
      protocol: TCP
    - port: 55555
      protocol: TCP
    - port: 60943
      protocol: TCP
    - port: 60080
      protocol: TCP
    - port: 60443
      protocol: TCP
storage:
  persistent: false
